{# archivo de dependencias -#}
{# testing spaces -#}
name: {{ cookiecutter.project_slug }}

channels:
 - conda-forge

dependencies:
  {% if cookiecutter.project_packages == "All" -%}

  - fs
  - jupyter
  - jupyterlab
  - pathlib
  {% endif -%}

  - pip
  {% if cookiecutter.project_packages == "All" -%}
  - pyprojroot
  {% endif -%}
  - python={{ cookiecutter.python_version }}
  - pip:
  {% if cookiecutter.project_packages == "All" -%}
<<<<<<< HEAD
    - pyhere
=======
   - pyhere
>>>>>>> 3bbe801ce1bd1dc9801c084fd94f39c23509a6fb
  {% endif -%}
